// <auto-generated />
using MVCPizza1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVCPizza1.Migrations
{
    [DbContext(typeof(OrdenDbContext))]
    partial class OrdenDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("MVCPizza1.Models.Orden", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ingredientes")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextoOrden")
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoMasa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TipoTamano")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ordenes");
                });
#pragma warning restore 612, 618
        }
    }
}
